--1
SELECT DISTINCT FABRICANTE, PRODUCTO FROM LINEAS_PEDIDOS
WHERE codigo in ( SELECT CODIGO FROM PEDIDOS 
WHERE EXTRACT (YEAR FROM fpedido) BETWEEN 1997 AND 1999);

--2
SELECT NOMBRE, TRUNC(MONTHS_BETWEEN(sysdate,fnacimiento)/12) AS "EDAD" FROM EMPLEADOS
    WHERE IDEMPLEADO IN ( SELECT IDVENDEDOR FROM PEDIDOS 
    WHERE EXTRACT (YEAR FROM fpedido) = 1997);
   
--3    
SELECT NOMBRE FROM CLIENTES 
    WHERE REPRESENTANTE IN ( SELECT IDEMPLEADO FROM EMPLEADOS
    WHERE LOWER(NOMBRE) LIKE 'raul aldamiz %');

--4    
SELECT NOMBRE FROM EMPLEADOS
    WHERE jefe IN (SELECT IDEMPLEADO FROM EMPLEADOS
    WHERE LOWER(NOMBRe) LIKE 'luis amezti %');

--5
SELECT CIUDAD,REGION,VENTAS FROM OFICINAS
    WHERE DIRECTOR IN (SELECT IDEMPLEADO FROM EMPLEADOS 
    WHERE LOWER(NOMBRE) LIKE 'miguel estrella %');

--6
SELECT DESCRIPCION, punitario || ' €' FROM PRODUCTOS
WHERE PUNITARIO IN (SELECT MIN(PUNITARIO) FROM PRODUCTOS);

--7
SELECT DESCRIPCION, punitario || ' €' FROM PRODUCTOS
WHERE PUNITARIO IN (SELECT MIN(PUNITARIO) FROM PRODUCTOS
WHERE LOWER (IDFABRICANTE) LIKE 'asa') AND LOWER (IDFABRICANTE) LIKE 'asa';

