CREATE TABLE P_OFICINAS (
    idOficina CHAR(2) CONSTRAINT PK_OFICINAS PRIMARY KEY,
    ciudad VARCHAR2(15),
    region VARCHAR2(10) CONSTRAINT CK_REGION CHECK(UPPER(region) IN ('NORTE','CENTRO','SUR','ESTE','OESTE')),
    dir NUMBER(3),
    objetivo NUMBER (10),
    ventas NUMBER (10)
); 
drop table P_OFICINAS;

CREATE TABLE P_EMPLEADOS(
    numEmp NUMBER(3),
    nombre VARCHAR2(20) CONSTRAINT NN_NOMBRE_EMPLEADO NOT NULL,
    edad NUMBER(2),
    oficina CHAR(2) CONSTRAINT FK_OFICINA REFERENCES P_OFICINAS (idOficina),
    titulo VARCHAR2(25) CONSTRAINT CK_TITULO_EMPLEADO CHECK(LOWER(titulo) in ('representante','dir ventas','dir general')),
    contrato DATE,
    jefe NUMBER(3),
    cuota NUMBER(10),
    ventas NUMBER(10),
    CONSTRAINT PK_P_EMP PRIMARY KEY (numEmp),
    CONSTRAINT U_NOMBRE_EMPLEADO UNIQUE (nombre),  
    CONSTRAINT CK_EDAD_EMPLEADO CHECK (edad >= 18 AND edad <= 65)
);
DROP TABLE P_EMPLEADOS;
select * FROM USER_TABLES;
commit;


CREATE TABLE P_CLIENTES(
    numCliente NUMBER(4),
    nombre VARCHAR2(25) CONSTRAINT NN_NOMBRE_CLIENTE NOT NULL,
    repClie NUMBER(3),
    limiteCredito NUMBER(9) DEFAULT 20000,
    CONSTRAINT PK_P_CLIENTE PRIMARY KEY (numCliente),
    CONSTRAINT U_NOMBRE_CLIENTE UNIQUE (nombre),
    CONSTRAINT FK_CLIENTE_EMPLEADOS FOREIGN KEY (repClie) REFERENCES P_EMPLEADOS(numEmp)
);
DROP TABLE P_CLIENTES;


CREATE TABLE P_PRODUCTOS(
    idFab CHAR(3),
    idProducto CHAR(5),
    descripcion VARCHAR2(20) CONSTRAINT NN_DESCRIPCION_PRODUCTOS NOT NULL,
    precio NUMBER (4),
    existencias NUMBER (3),
    CONSTRAINT PK_P_PRODUCTOS PRIMARY KEY (idFab, idProducto),
    CONSTRAINT PK_P_PRODUCTOS_PRECIO CHECK (precio > 0)
    
);
drop table P_PRODUCTOS;

CREATE TABLE P_PEDIDOS (
    codigo NUMBER(3),
    numPedido NUMBER (6),
    fechaPedido DATE,
    clie NUMBER(4),
    Repre NUMBER(3),
    fab CHAR(3),
    producto CHAR(5),
    cantidad NUMBER (2),
    importe NUMBER(10),
    CONSTRAINT PK_P_PEDIDOS PRIMARY KEY (codigo),
    CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (clie) REFERENCES P_CLIENTES(numCliente),
    CONSTRAINT FK_PEDIDOS_REPRE FOREIGN KEY (repre) REFERENCES P_EMPLEADOS(numEmp),
    CONSTRAINT FK_PEDIDOS_PRODUCTOS FOREIGN KEY (fab, producto) REFERENCES P_PRODUCTOS(idFab, idProducto),
    CONSTRAINT CK_P_PEDIDOS CHECK (importe > 0)
);
DROP TABLE P_PEDIDOS;


select * FROM USER_TABLES;
SELECT * FROM USER_TAB_COLUMNS WHERE LOWER(TABLE_NAME)='p_pedidos';


