DECLARE 
V_IDCLIENTE clientes.idcliente%TYPE;
V_NOMBRE clientes.nombre%TYPE;
V_PEDIDOS NUMBER(4);
V_GASTADO NUMBER(10);
BEGIN 
V_IDCLIENTE:=&identificativo_del_cliente;
VER_DATOS_CLIENTES_v2(V_IDCLIENTE,V_NOMBRE,V_PEDIDOS,V_GASTADO);

    DBMS_OUTPUT.PUT_LINE('NOMBRE CLIENTE:' || V_NOMBRE);
 
  IF V_PEDIDOS = 0 THEN 

    DBMS_OUTPUT.PUT_LINE('EL CLIENTE NO TIENE PEDIDOS');

  ELSE
    DBMS_OUTPUT.PUT_LINE('NUMERO DE PEDIDOS:' || V_PEDIDOS);
    DBMS_OUTPUT.PUT_LINE('TOTAL GASTADO:' || V_GASTADO);
  END IF;

END;