CREATE TABLE LIBROS(
    idLibro CHAR(5) CONSTRAINT PK_LIBROS PRIMARY KEY,
    titulo VARCHAR2(20) CONSTRAINT NN_TITULO NOT NULL CONSTRAINT U_TITULO UNIQUE,
    tipo VARCHAR2(10) CONSTRAINT CK_TIPO CHECK(LOWER(tipo) IN ('novela','terror','misterio')),
    editor VARCHAR2(25),
    fechaEdicion DATE
);

DESC LIBROS;

SELECT * FROM USER_TABLES;
SELECT * FROM USER_TAB_COLUMNS WHERE LOWER(TABLE_NAME)='libros';
SELECT * FROM USER_CONS_COLUMNS WHERE LOWER(TABLE_NAME)='libros';


CREATE TABLE AUTORES(
    idAutor CHAR(4) CONSTRAINT PK_AUTORES PRimary KEY,
    nombreAutor VARCHAR2(25) CONSTRAINT NN_NOMBRE_AUTORES NOT NULL,
    telefono CHAR(9) CONSTRAINT CK_TELEFONO_AUTORES CHECK (telefono LIKE '94%'),
    direccion VARCHAR2(50),
    poblacion VARCHAR2(30),
    provincia VARCHAR2(25) CONSTRAINT CK_PROVINCIA_AUTORES CHECK(LOWER(provincia) IN ('bizkaia','guipuzkoa','Araba'))
);

DESC AUTORES;
SELECT * FROM USER_TABLES;
SELECT * FROM USER_TAB_COLUMNS WHERE LOWER(TABLE_NAME)='autores';
SELECT * FROM USER_CONS_COLUMNS WHERE LOWER(TABLE_NAME)='autores';

--TABLA AUTOR LIBRO REST 1
/*
ESTA HECHA CON RESTRICCION DE TIPO 1
CREATE TABLE AUTOR_LIBRO(
    libroID CHAR(5) CONSTRAINT FK_AUTOR_LIBRO_LIBRO REFERENCES LIBROS,
    autorID CHAR (4) CONSTRAINT FK_AUTOR_LIBRO_AUTORES REFERENCES AUTORES(idAutor),
    CONSTRAINT PK_AUTOR_LIBRO PRIMARY KEY (libroID, autorID)
);*/

--RESTRICCION DE TIOPO 2
CREATE TABLE AUTOR_LIBRO(
    libroID CHAR(5),
    autorID CHAR (4) ,
    CONSTRAINT PK_AUTOR_LIBRO PRIMARY KEY (libroID, autorID),
    CONSTRAINT FK_AUTOR_LIBRO_LIBROS FOREIGN KEY (libroID) REFERENCES LIBROS(idLibro),
    CONSTRAINT FK_AUTOR_LIBRO_AUTORES FOREIGN KEY (autorID) REFERENCES AUTORES(idAutor)
);

INSERT INTO LIBROS VALUES ('00001', 'Programacion Java', 'misterio', 'paraninfo', '10-10-2007');
INSERT INTO LIBROS VALUES ('00002', 'Base de Datos ORACLE', 'misterio', 'paraninfo', '10-12-2005');

INSERT INTO AUTORES VALUES('0001', 'Iñigo' , '944163195', 'C/Esperanza 12', 'Bilbao', 'Bizkaia');
INSERT INTO AUTORES VALUES('0002', 'Marta' , '944163195', 'C/Esperanza 12', 'Bilbao', 'Bizkaia');

SELECT * FROM LIBROS;
SELECT * FROM AUTORES;

INSERT INTO AUTOR_LIBRO VALUES ('00001','0001');
INSERT INTO AUTOR_LIBRO VALUES ('00002','0002');
INSERT INTO AUTOR_LIBRO VALUES ('00002','0001');

SELECT titulo,tipo,fechaedicion FROM LIBROS WHERE UPPER(titulo) LIKE '% JAVA%';
SELECT titulo,tipo,fechaedicion 
    FROM LIBROS 
    WHERE UPPER(editor)='PARANINFO'
    ORDER BY titulo;
    
SELECT nombreAutor,titulo 
    FROM autores a,libros l, autor_libro al
    WHERE   a.idautor = al.autorid  AND l.idlibro = al.libroid;

commit;

