CREATE TABLE LIBROS(
    idLibro CHAR(5) CONSTRAINT PK_LIBROS PRIMARY KEY,
    titulo VARCHAR2(20) CONSTRAINT NN_TITULO NOT NULL CONSTRAINT U_TITULO UNIQUE,
    tipo VARCHAR2(10) CONSTRAINT CK_TIPO CHECK(LOWER(tipo) IN ('novela','terror','misterio')),
    editor VARCHAR2(25),
    fechaEdicion DATE
);